# Generated by Django 5.0.6 on 2024-07-06 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_doctor_managers_alter_patient_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Bachelor <django.db.models.query_utils.DeferredAttribute object at 0x0000011E16CF4070>',
            new_name='Bachelor <django.db.models.query_utils.DeferredAttribute object at 0x000001B05443B910>',
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='Master <django.db.models.query_utils.DeferredAttribute object at 0x0000011E16CF4070>',
            new_name='Master <django.db.models.query_utils.DeferredAttribute object at 0x000001B05443B910>',
        ),
    ]
