# Generated by Django 5.0.6 on 2024-07-12 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0002_alter_patient_managers_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseasePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title of post')),
                ('description', models.TextField(verbose_name='Description of post')),
                ('intensity', models.IntegerField(verbose_name='Intensity')),
                ('files_1', models.FileField(default=None, null=True, upload_to='images/files/', verbose_name='Attachment № 1')),
                ('files_2', models.FileField(default=None, null=True, upload_to='images/files/', verbose_name='Attachment № 2')),
                ('files_3', models.FileField(default=None, null=True, upload_to='images/files/', verbose_name='Attachment № 3')),
                ('poster', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='management.user', verbose_name="Disease Post's poster")),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content of Comment')),
                ('likes', models.IntegerField(null=True, verbose_name='Likes of comment')),
                ('dislikes', models.IntegerField(null=True, verbose_name='Dislikes of comment')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentator', to='management.user', verbose_name='Commentator')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='forum.diseasepost', verbose_name="Post's comment")),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
